Add user module
bmstu-secret-chat/secret_chat-backend pull request #4
Opened 2024-12-08 17:02 UTC by arklem699

2024-12-09 08:34 UTC, DriverOnLips requested changes

2024-12-09 08:34 UTC, DriverOnLips commented on backend/settings.py
> +ALLOWED_HOSTS = ['*']
как добавить пути в оркестратор, поставь доступы только с локального хоста

2024-12-09 08:34 UTC, DriverOnLips commented on users/managers.py
> +        user.set_password(password)
тут есть хеширование? какой алгоритм?

2024-12-29 14:19 UTC, DriverOnLips commented on backend/middleware.py
> +        if any(request.path_info.startswith(path) for path in self.ALLOWED_PATHS):
не лучше сделать includes для /users/create и тд, что апи/бек не тащить

2024-12-31 13:00 UTC, arklem699 commented on backend/middleware.py
> +        if any(request.path_info.startswith(path) for path in self.ALLOWED_PATHS):
такого метода нет, а костыль писать так себе идея. вынес префикс в отдельную переменную

2024-12-31 19:49 UTC, DriverOnLips approved these changes

2024-12-31 19:49 UTC, merged